import { Question } from '@/types';

export const questions: Question[] = [
  {
    id: 'origin',
    category: 'Trip basics',
    question: 'Where will you be traveling from?',
    type: 'text',
    placeholder: 'City or nearest airport',
  },
  {
    id: 'duration',
    category: 'Trip basics',
    question: 'How long would you like to travel for?',
    type: 'single',
    options: ['A weekend', 'Five to seven days', 'One to two weeks', 'Longer'],
  },
  {
    id: 'timing',
    category: 'Trip basics',
    question: 'When are you hoping to go?',
    type: 'single',
    options: ['I have specific dates', "I'm flexible", "I'm not sure yet"],
  },
  {
    id: 'travelers',
    category: 'Trip basics',
    question: 'Who will be traveling?',
    type: 'single',
    options: ['Just me', 'Two of us', 'Family', 'Group'],
  },
  {
    id: 'groupSize',
    category: 'Trip basics',
    question: 'How many people in your group?',
    type: 'slider',
    min: 3,
    max: 20,
    step: 1,
    conditionalOn: { field: 'travelers', value: 'Group' },
  },
  {
    id: 'travelVibe',
    category: 'Your vibe',
    question: 'Which feeling calls to you most?',
    type: 'image-select',
    imageOptions: [
      {
        id: 'cozy-retreat',
        label: 'Cozy retreat',
        images: [
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&q=80',
          'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=400&q=80',
          'https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?w=400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&q=80',
        ],
      },
      {
        id: 'urban-energy',
        label: 'Urban energy',
        images: [
          'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=400&q=80',
          'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400&q=80',
          'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&q=80',
          'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&q=80',
        ],
      },
      {
        id: 'wild-nature',
        label: 'Wild nature',
        images: [
          'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&q=80',
          'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400&q=80',
          'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=400&q=80',
          'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=400&q=80',
        ],
      },
      {
        id: 'beach-bliss',
        label: 'Beach bliss',
        images: [
          'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
          'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=400&q=80',
          'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=400&q=80',
          'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=400&q=80',
        ],
      },
      {
        id: 'cultural-immersion',
        label: 'Cultural immersion',
        images: [
          'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400&q=80',
          'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400&q=80',
          'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=400&q=80',
          'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=400&q=80',
        ],
      },
      {
        id: 'adventure-thrill',
        label: 'Adventure thrill',
        images: [
          'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&q=80',
          'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?w=400&q=80',
          'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80',
          'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=400&q=80',
        ],
      },
    ],
  },
  {
    id: 'budget',
    category: 'Budget & comfort',
    question: 'Do you have a budget in mind?',
    type: 'budget',
    min: 500,
    max: 10000,
    step: 100,
  },
  {
    id: 'budgetPriority',
    category: 'Budget & comfort',
    question: 'Where would you happily spend more?',
    type: 'single',
    options: [
      'The hotel - I want to wake up somewhere special',
      'The food - dining is a highlight for me',
      'Experiences - tours, tickets, and activities',
      'Convenience - taxis, direct flights, less hassle',
    ],
  },
  {
    id: 'accommodation',
    category: 'Budget & comfort',
    question: 'How would you like to stay?',
    type: 'multi',
    options: [
      'Boutique hotels',
      'Luxury stays',
      'Budget-friendly options',
      'Apartments or Airbnbs',
      'Unique stays',
    ],
  },
  {
    id: 'perfectMorning',
    category: 'Your style',
    question: "It's 10 AM on your second day. What are you doing?",
    type: 'single',
    options: [
      'Still sleeping in, no alarms on vacation',
      'Already at a museum or landmark',
      'Hiking a trail or exploring outdoors',
      'Finding the best local coffee spot',
      'At a market picking up fresh pastries',
    ],
  },
  {
    id: 'pace',
    category: 'Your style',
    question: 'What pace feels right for this trip?',
    type: 'single',
    options: ['Slow and relaxed', 'Balanced', 'Full and energetic'],
  },
  {
    id: 'personality',
    category: 'Your style',
    question: 'Where do you fall on these?',
    type: 'binary-toggles',
    binaryToggles: [
      { id: 'plannedVsSpontaneous', leftLabel: 'Planned itinerary', rightLabel: 'Spontaneous discovery' },
      { id: 'comfortVsAuthenticity', leftLabel: 'Comfort first', rightLabel: 'Authenticity first' },
      { id: 'famousVsHidden', leftLabel: 'Famous spots', rightLabel: 'Hidden gems' },
    ],
  },
  {
    id: 'lovedTrips',
    category: 'Preferences',
    question: "Trips you've loved before",
    type: 'text',
    placeholder: 'Tell us about a trip that felt just right',
    optional: true,
  },
  {
    id: 'dislikedTrips',
    category: 'Preferences',
    question: "Trips that didn't quite work for you",
    type: 'text',
    placeholder: 'What made them less enjoyable?',
    optional: true,
  },
  {
    id: 'interests',
    category: 'Preferences',
    question: 'What do you most enjoy while traveling?',
    type: 'multi',
    options: [
      'Great food',
      'Culture and history',
      'Nature and scenery',
      'Adventure and activity',
      'Rest and relaxation',
      'Nightlife and social scenes',
    ],
  },
  {
    id: 'foodStyle',
    category: 'Preferences',
    question: 'What kind of food experiences excite you?',
    type: 'multi',
    conditionalOn: { field: 'interests', value: ['Great food'] },
    options: [
      'Street food and markets',
      'Fine dining and tasting menus',
      'Cooking classes',
      'Local staples and hole-in-the-wall spots',
      'Wine, coffee, or cocktail culture',
    ],
  },
  {
    id: 'travelStyle',
    category: 'Preferences',
    question: 'Which descriptions feel most like you?',
    type: 'multi',
    options: [
      'Calm and scenic',
      'Lively and social',
      'Quiet and remote',
      'Iconic and must-see',
      'Local and understated',
    ],
  },
  {
    id: 'avoidances',
    category: 'Practicalities',
    question: "Anything you'd prefer to avoid?",
    type: 'multi',
    options: [
      'Long flights',
      'Busy crowds',
      'Extreme heat',
      'Cold climates',
      'Driving',
    ],
  },
  {
    id: 'tripRuiners',
    category: 'Practicalities',
    question: 'What tends to ruin a trip for you?',
    type: 'multi',
    options: [
      'Feeling rushed',
      'Tourist traps',
      'Uncomfortable beds',
      'Confusing public transit',
      'Bad weather surprises',
      'Lack of good food options',
    ],
  },
  {
    id: 'dietaryNeeds',
    category: 'Practicalities',
    question: 'Any dietary or accessibility needs?',
    type: 'text',
    placeholder: 'Let us know if there are any requirements',
    optional: true,
  },
  {
    id: 'mustIncludes',
    category: 'Practicalities',
    question: 'Anything this trip should include?',
    type: 'text',
    placeholder: 'Specific experiences or places',
    optional: true,
  },
  {
    id: 'intention',
    category: 'Intention',
    question: "If this trip goes perfectly, you'll feel...",
    type: 'single',
    options: ['Rested', 'Inspired', 'Energized', 'Connected', 'Adventurous'],
  },
];
